services:
  catalogue:
    build:
      context: ./catalogue
      dockerfile: dockerfile
    image: akhila2829/catalogue:v1
    container_name: catalogue
    depends_on: 
    - mongodb
  mongodb: 
    build: ./mongodb
    image: akhila2829/mongodb:v1
    container_name: mongodb
  redis: 
    image: redis:7.0
    container_name: redis
    volumes:
    - redis:/data
  mysql:
    build: ./mysql
    image: akhila2829/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  user:
    build: ./user
    image: akhila2829/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    build: ./cart
    image: akhila2829/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  shipping:
    build: ./shipping
    image: akhila2829/shipping:v1
    container_name: shipping
    depends_on: 
    - mysql
    - cart
  payment:
    build: ./payment
    image: akhila2829/payment:v1
    container_name: payment
    depends_on: 
    - rabbitmq
    - cart
    - user
  frontend:
    build: ./frontend
    image: akhila2829/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment            
networks:
  default:
    driver: bridge
    name: roboshop
    external: false  
volumes:
  mongodb:
  redis:
  mysql:  
  rabbitmq: